### ISSUE TITLE
Could you make a release?

### ISSUE THREAD

**Issue by daurnimator** [mjsottile/sfsexp#19]
There are several fixes in master I'd love to see in a release

**Comment by mjsottile** [comment]
Yes.  Currently backlogged with the day job but plan to do one soon.

**Comment by mjsottile** [comment]
v1.4.0 released

**Comment by daurnimator** [comment]
Thanks.
A sfsexp package is now available in ArchLinux. https://archlinux.org/packages/community/x86_64/sfsexp
